services:
  db:
    image: mysql:8.0.36-debian
    container_name: mysql-tarefasdb
    environment:
      MYSQL_ROOT_PASSWORD: root_tarefas_2024#
      MYSQL_DATABASE: tarefasdb
      MYSQL_PASSWORD: minha-senha
    ports:
      - "3306:3306"