version: '3.8'

services:
  db:
    image: mysql:8.0.36-debian
    container_name: mysql-tarefasdb
    environment:
      MYSQL_ROOT_PASSWORD: root_tarefas_2024#
      MYSQL_DATABASE: tarefasdb
      MYSQL_PASSWORD: minha-senha
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: desafiotarefadev
    container_name: gerenciador_tarefa_app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "80:80"
    depends_on:
      - db